### PR TITLE
Update to modern

### PR DESCRIPTION
**Pull request by jfarid27**
I also played around with the metaprogramming and I wanted to update this to modern julia. This implementation is slightly different since I hack the expressions to keep the ```<-``` operator.

I'd also recommend adding this to the new packages repo, which I could help out with.

CC: @ulysses4ever

### CODE REVIEW

**Comment by ulysses4ever** [comment]
Speaking about `->`, I made support for it at the beginning, but then preferred to switch to `<|`. I cannot remember why, but, I guess, there was a reason.

**Comment by ulysses4ever** [comment]
Second, I don't think it is necessary to write `.value` in test since there is a `==`-method for `MList` doing exactly this (after all this is the whole point of Julia: instead of duplicating things, just wrap them into suitable method).

Otherwise, I think we could compose a TODO-list:

- [ ] publish our update in METADATA.jl. As @pao doesn't respond for quite some time, we could try to “take over” the package (as [it is called in Haskell](https://wiki.haskell.org/Taking_over_a_package), no offence). 
- [ ] add some tests for various instances of `Monad`s and `MonadPlus`.
- [ ] add more monads: Reader/Writer/State.
- [ ] check the performance. I recently add this to my project and noticed significant slowdown. Maybe it is due to some other changes, but still basic benchmarking is very much appreciated, I think.

**Comment by pao** [comment]
Didn't even realize there was traffic here. I can blind pull (this will not be reviewed by me as I have no idea what's going on and lack the motivation to catch up) or will happily donate this if someone wishes to take over maintenance.

**Comment by ulysses4ever** [comment]
@pao maybe it will suffice to add @jfarid27 and me as this project's collaborators? Any thoughts, @jfarid27? I don't have deep understanding of how Julia's ecosystem work, so I'm not sure if it's easy to change the whole repo for the project in METADATA.jl.

**Comment by pao** [comment]
Can certainly do that, stand by...

**Comment by ulysses4ever** [comment]
Thanks so much, @pao!

**Comment by jfarid27** [comment]
@ulysses4ever @pao I wouldn't mind helping to maintain. As for stuff to do, last night I did get some of the tests working, but it was mostly a matter of importing the project correctly. I want to formally open a few issues touching the stuff @ulysses4ever mentioned to get the project back on the packages list, but I just have to read through the docs. I believe it's as simple as a few commands to get it back on the list of available packages.

**Comment by ulysses4ever** [comment]
@jfarid27 issues are good!

**Comment by jfarid27** [comment]
Also, thanks @pao. Hopefully this gets added soon to the repos and picks up.

**Pull request merged**
