### PR TITLE
don't rely on reduce being fold-left (fix #3)

### LINKED ISSUE #3: Don't rely on reduce being fold-left
As you mentioned today, the code

```
mdo_desugar(exprIn) = reduce(mdo_desugar_helper, :(), reverse(exprIn.args))
```

assumes that the associativity of `reduce` is fold-left, which is true of the current implementation but is undocumented, and may change (JuliaLang/julia#4046).

In any case,

```
function mdo_desugar(exprIn)
    r = :()
    for i = length(exprIn.args):-1:1
        r = mdo_desugar_helper(exprIn.args[i], r)
    end
    r
end
```

has the additional virtue of being faster (since it avoids the call to `reverse` and the allocation of a new array), not that it probably matters to you.

### PR DESCRIPTION
**Pull request by stevengj**
Fixes #3.

### CODE REVIEW

**Comment by stevengj** [comment]
Travis failure seems unrelated (`rake` not found)

**Comment by jfarid27** [comment]
@stevengj @ulysses4ever The PR seems to not pass our (arguably minimal) tests. Although I think you're right Steven that it should be a foldLeft, so it's likely a bug in the implementation of MList.

**Comment by ulysses4ever** [comment]
oops, sorry: it seems, I was too fast to merge

**Comment by jfarid27** [comment]
@ulysses4ever It's ok! I think the issue is it needs to be a foldL. After switching it to a foldL, the implementation breaks at MList. I'm staring at it now!

**Pull request merged**
